# Notebook Overview
This Test Uses an  linearregression model from sklearn to determine if it is a true linear problem also data is unscaled

In [1]:
# Import libraries. You may or may not use all of these.
!pip install -q git+https://github.com/tensorflow/docs
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras.layers import Dense

import tensorflow_docs as tfdocs
import tensorflow_docs.plots
import tensorflow_docs.modeling

  Preparing metadata (setup.py) ... done
  Building wheel for tensorflow-docs (setup.py) ... done
Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.

In [4]:
# Import data
!wget https://cdn.freecodecamp.org/project-data/health-costs/insurance.csv
dataset = pd.read_csv('insurance.csv')

--2026-05-25 17:10:01--  https://cdn.freecodecamp.org/project-data/health-costs/insurance.csv
Resolving cdn.freecodecamp.org (cdn.freecodecamp.org)... 104.26.2.33, 104.26.3.33, 172.67.70.149, ...
Connecting to cdn.freecodecamp.org (cdn.freecodecamp.org)|104.26.2.33|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 50264 (49K) [text/csv]
Saving to: ‘insurance.csv’

insurance.csv       100%[===================>]  49.09K  --.-KB/s    in 0.001s

2026-05-25 17:10:02 (53.4 MB/s) - ‘insurance.csv’ saved [50264/50264]

In [5]:
dataset.tail()

      age     sex   bmi  children smoker     region  expenses
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

In [6]:
# size of dataset
dataset.shape

(1338, 7)

In [7]:
# investigating for null values

dataset.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
expenses    0
dtype: int64

In [8]:
# isolating labels

labels = dataset.pop("expenses")

In [9]:
# unique regions
dataset['region'].nunique()

4

In [10]:
dataset.head()

   age     sex   bmi  children smoker     region
0   19  female  27.9         0    yes  southwest
1   18    male  33.8         1     no  southeast
2   28    male  33.0         3     no  southeast
3   33    male  22.7         0     no  northwest
4   32    male  28.9         0     no  northwest

In [11]:
# converting categorical columns to onehot encode

categorical = ["sex","smoker","region"]
# drop first column for statistical significance

dataset = pd.get_dummies(dataset, columns = categorical, drop_first = True)

In [12]:
dataset.head()

,age,bmi,children,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.9,0,False,True,False,False,True
1,18,33.8,1,True,False,False,True,False
2,28,33.0,3,True,False,False,True,False
3,33,22.7,0,True,False,True,False,False
4,32,28.9,0,True,False,True,False,False

In [14]:
X = dataset.values
Y = labels.values

In [15]:
# split and shuffle
from sklearn.model_selection import train_test_split

train_dataset,test_dataset,train_labels,test_labels = train_test_split(X,Y,test_size = 0.2,random_state = 42)

In [16]:
# using linear model

from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [17]:
# fitting

model.fit(train_dataset,train_labels)

LinearRegression()

In [18]:
from sklearn.metrics import mean_absolute_error

In [19]:
y_pred = model.predict(test_dataset)

In [20]:
mean_absolute_error(test_labels,y_pred)

4181.561524000792