# Notebook Overview

This Notebook shows use case for Predicting diabetes using K Nearest neighbours to better understand the upcoming KNN Book Reccomendation project

In [1]:
# importing tools
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

In [2]:
from google.colab import files as f
# load dataset
uploaded = f.upload()

Saving diabetes.csv to diabetes.csv

In [3]:
df_train = pd.read_csv("diabetes.csv")

In [4]:
df_train.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [5]:
len(df_train)

768

In [6]:
# Replace Zeros with NAN
# fill the nan place holders with the columns mean

zero_columns = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',]

for c in zero_columns:
  df_train[c] = df_train[c].replace(0,np.nan).fillna(df_train[c].mean())

In [7]:
# extracting columns
columns = df_train.columns.tolist()
print(columns)

['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']

In [8]:
# split dataset
# iloc integer location
# df.iloc[row_index, column_index]

'''
selects all rows and feauture,labels columns
'''

features = df_train.iloc[:, 0:8]
labels = df_train.iloc[:, -1] # selcts last column

X_train, X_test, y_train, y_test = train_test_split(features,labels,test_size= 0.2, random_state = 0)

# Standard Scaler

Standardize features by removing the mean and scaling to unit variance.

The standard score of a sample x is calculated as:


    z = (x - u) / s

where `u` is the mean of the training samples or zero if `with_mean=False`,
and `s` is the standard deviation of the training samples or one if
`with_std=False`.

Centering and scaling happen independently on each feature by computing
the relevant statistics on the samples in the training set. Mean and
standard deviation are then stored to be used on later data using
:meth:`transform`.

Standardization of a dataset is a common requirement for many
machine learning estimators: they might behave badly if the
individual features do not more or less look like standard normally
distributed data (e.g. Gaussian with 0 mean and unit variance).

In [9]:
# feature scaling btw 1 & -1
# to avoid large numbers and compare different units across same scale
scaler = StandardScaler().set_output(transform='pandas')
X_train = scaler.fit_transform(X_train)

# transform using the training standard dev and average
# this avoids confusing the model and correct predictions
X_test = scaler.transform(X_test)

# Quick check to ensure scaling looks correct
display(X_train.head())

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
603,0.908329,0.936440,0.458160,0.235913,0.059279,0.368650,0.677404,1.699558
118,0.036447,-0.816286,-1.038640,-0.382505,-0.425194,-0.632929,-0.070497,-0.965692
247,-1.126063,1.432495,1.456028,0.648191,5.868693,2.815363,-0.118555,-0.882403
157,-0.835435,-0.419442,-1.371263,-0.588644,0.153656,-1.062177,1.100914,-0.882403
468,1.198956,-0.055669,-0.281470,-0.636421,-0.425194,-0.375380,-0.851438,0.366933

p : float, default=2
    Power parameter for the Minkowski metric. When p = 1, this is equivalent
to using manhattan_distance (l1), and euclidean_distance (l2) for p = 2.
For arbitrary p, minkowski_distance (l_p) is used. This parameter is expected
to be positive.

metric : str or callable, default='minkowski'

In [10]:
classifier = KNeighborsClassifier(n_neighbors=11, p=2, metric='euclidean')

In [11]:
# Fit the model with training data
classifier.fit(X_train, y_train)

# Now make predictions
y_pred = classifier.predict(X_test)

In [13]:
distances, indices = classifier.kneighbors(X_test)

print("Distances to 11 nearest neighbors for the first 5 test samples:\n", distances[:5])
print("Indices of 11 nearest neighbors for the first 5 test samples:\n", indices[:5])

Distances to 11 nearest neighbors for the first 5 test samples:
 [[1.91472289 2.3937326  2.52406384 2.69945593 2.72978555 2.82525893
  2.88206994 3.02580446 3.04861308 3.08913279 3.19422268]
 [0.80801458 0.86374309 0.90264362 0.91153778 0.92454057 0.95727108
  0.97682018 0.98981617 0.99508502 0.9990846  1.00348772]
 [0.94569433 1.00932821 1.01036362 1.10965736 1.16082138 1.1618771
  1.16228418 1.16283466 1.17820533 1.24668935 1.24725233]
 [1.41876621 1.83037839 1.83774223 1.85210482 1.85916014 1.87669459
  1.93308626 1.93387599 1.93612361 1.94536633 2.00787324]
 [0.89769119 1.06839003 1.14260166 1.18862067 1.2319264  1.26820476
  1.30676897 1.30886127 1.33401667 1.34502459 1.38336359]]
Indices of 11 nearest neighbors for the first 5 test samples:
 [[ 29 521 268 607 310 519 234 238 318 344  68]
 [551 278  21 538  79 220 498 574 470 198 388]
 [143 241 132  66 566   1 516 281 592 261 428]
 [484   6 147 259 507 402 359 216 280 482 610]
 [174 403 604 392 149 421   3 330 181 217  13]]

In [15]:
df_train.iloc[29, :]

Pregnancies                   5.000000
Glucose                     117.000000
BloodPressure                92.000000
SkinThickness                20.536458
Insulin                      79.799479
BMI                          34.100000
DiabetesPedigreeFunction      0.337000
Age                          38.000000
Outcome                       0.000000
Name: 29, dtype: float64

The `kneighbors` method returns two arrays:

*   `distances`: An array where each row contains the distances from a test sample to its `n_neighbors` closest training samples.
*   `indices`: An array where each row contains the indices of those `n_neighbors` closest training samples in the original `X_train` dataset.

In [12]:
# Evaluate Model
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

print(f"F1 Score: {f1_score(y_test, y_pred):.2f}")
print(f"Accuracy Score: {accuracy_score(y_test, y_pred):.2f}")

Confusion Matrix:
[[97 10]
 [21 26]]
F1 Score: 0.63
Accuracy Score: 0.80

### Precision and Recall Formulas

**Precision** measures the accuracy of the positive predictions. It is the ratio of correctly predicted positive observations to the total predicted positive observations.

$Precision = \frac{\text{True Positives (TP)}}{\text{True Positives (TP)} + \text{False Positives (FP)}}$

**Recall** (also known as Sensitivity) measures the ability of the classifier to find all the positive samples. It is the ratio of correctly predicted positive observations to all observations in the actual class.

$Recall = \frac{\text{True Positives (TP)}}{\text{True Positives (TP)} + \text{False Negatives (FN)}}$